version: "3.7"

services:
  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql

  app:
    build:
      context: .
    restart: always
    volumes:
      - static_data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db"
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
  postgres-data:
