version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: gcr.io/groovy-legacy-814/django-rest-udemy
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    expose:
      - 8000
    env_file:
      - ./environments/.env.prod
    depends_on:
      - db

  db:
    image: postgres:10.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./environments/.env.prod.db

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    image: gcr.io/groovy-legacy-814/django-rest-udemy-nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./environments/.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
