# Generated by Django 2.1.15 on 2021-02-08 18:06

import corex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=corex.models.recipe_image_file_path),
        ),
    ]
